"use client";
import {useGLTF} from "@react-three/drei";
import {useFrame,useThree} from "@react-three/fiber";
import {useEffect,useMemo,useRef} from "react";
import {Box3,Color,Group,Material,MathUtils,Mesh,MeshStandardMaterial,Quaternion,Vector3} from "three";
import {SkeletonUtils} from "three/examples/jsm/Addons.js";
import {expectedMeshes,getInspectionIndex,inspectionLocal,inspections,MeshName} from "../content/story";
import {mix,range,smooth} from "../controllers/math";
import {EXPLOSION,RECONSTRUCTION,storyPose} from "../controllers/sceneTimeline";
import type {ExperienceBridge} from "../experienceTypes";

type Original={position:Vector3;quaternion:Quaternion;scale:Vector3;colors:Color[]};
const DISTANCE_RATIO:Record<MeshName,number>={TopShell:1,UpperFilo:.52,Pistachio:0,LowerFilo:-.52,BaseShell:-1};
const CLOSED:Record<MeshName,number>={TopShell:0,UpperFilo:0,Pistachio:0,LowerFilo:0,BaseShell:0};
const EPSILON=.0005,DIRECTION_BLEND=.08;
function segmentProgress(progress:number,start:number,end:number){return smooth(range(progress,start,end))}
function explosionProgress(pageProgress:number){if(pageProgress<EXPLOSION.start)return 0;if(pageProgress<=EXPLOSION.end)return range(pageProgress,EXPLOSION.start,EXPLOSION.end);if(pageProgress<RECONSTRUCTION.start)return 1;if(pageProgress<RECONSTRUCTION.end)return 1-range(pageProgress,RECONSTRUCTION.start,RECONSTRUCTION.end);return 0}
function openingTransforms(progress:number):Record<MeshName,number>{return{TopShell:segmentProgress(progress,0,.2),UpperFilo:segmentProgress(progress,.2,.4),Pistachio:0,BaseShell:segmentProgress(progress,.55,.75),LowerFilo:segmentProgress(progress,.75,1)}}
function closingTransforms(progress:number):Record<MeshName,number>{const closing=1-progress;return{UpperFilo:1-segmentProgress(closing,0,.4),LowerFilo:1-segmentProgress(closing,0,.4),Pistachio:0,TopShell:1-segmentProgress(closing,.4,.7),BaseShell:1-segmentProgress(closing,.7,1)}}

export function SingleBaklava({bridge,pointer,onReady}:{bridge:ExperienceBridge;pointer:React.MutableRefObject<{x:number;y:number}>;onReady:()=>void}){
 const gltf=useGLTF("/Media/baklava.glb"),root=useRef<Group>(null),signaled=useRef(false),validatedClosed=useRef(false),debugTick=useRef(-1),direction=useRef<"opening"|"closing">("opening"),previousMaster=useRef(0),directionStart=useRef(0),directionSnapshot=useRef<Record<MeshName,number>>({...CLOSED}),currentOpenness=useRef<Record<MeshName,number>>({...CLOSED}),debugMode=useRef<"raw"|"animated"|null>(typeof window!=="undefined"?(new URLSearchParams(window.location.search).get("debug") as "raw"|"animated"|null):null),{size}=useThree();
 const prepared=useMemo(()=>{
  const scene=SkeletonUtils.clone(gltf.scene),meshes=new Map<MeshName,Mesh>(),offsets=new Map<MeshName,Group>();
  scene.traverse(child=>{if(!(child instanceof Mesh))return;if(!expectedMeshes.includes(child.name as MeshName))return;const array=Array.isArray(child.material),source=array?child.material:[child.material],materials=source.map((material:Material)=>{const clone=material.clone();clone.transparent=true;return clone});child.material=array?materials:materials[0];child.castShadow=true;child.receiveShadow=true;child.frustumCulled=false;meshes.set(child.name as MeshName,child)});
  const missing=expectedMeshes.filter(name=>!meshes.has(name));if(missing.length||meshes.size!==5)throw new Error(`Masa GLB mesh mismatch: ${missing.join(", ")||meshes.size}`);
  const originals=new Map<MeshName,Original>();meshes.forEach((mesh,name)=>{const materials=Array.isArray(mesh.material)?mesh.material:[mesh.material];originals.set(name,{position:mesh.position.clone(),quaternion:mesh.quaternion.clone(),scale:mesh.scale.clone(),colors:materials.map(material=>material instanceof MeshStandardMaterial?material.color.clone():new Color(1,1,1))})});
  expectedMeshes.forEach(name=>{const mesh=meshes.get(name)!,parent=mesh.parent;if(!parent)throw new Error(`Masa mesh has no parent: ${name}`);const wrapper=new Group();wrapper.name=`${name}OffsetGroup`;parent.add(wrapper);wrapper.add(mesh);offsets.set(name,wrapper)});
  scene.updateMatrixWorld(true);const box=new Box3(),centers=expectedMeshes.map(name=>new Box3().setFromObject(meshes.get(name)!).getCenter(new Vector3()));expectedMeshes.forEach(name=>box.expandByObject(meshes.get(name)!));const extent=box.getSize(new Vector3()),center=box.getCenter(new Vector3()),ranges={x:Math.max(...centers.map(value=>value.x))-Math.min(...centers.map(value=>value.x)),y:Math.max(...centers.map(value=>value.y))-Math.min(...centers.map(value=>value.y)),z:Math.max(...centers.map(value=>value.z))-Math.min(...centers.map(value=>value.z))},verticalKey=(Object.entries(ranges).sort((a,b)=>b[1]-a[1])[0][0] as "x"|"y"|"z"),verticalAxis=new Vector3(verticalKey==="x"?1:0,verticalKey==="y"?1:0,verticalKey==="z"?1:0),explosionDistance=extent[verticalKey]*.55,normalizer=1.32/Math.max(extent.x,extent.y,extent.z);scene.scale.setScalar(normalizer);scene.position.copy(center).multiplyScalar(-normalizer);
  if(process.env.NODE_ENV==="development")console.info("Masa · detected pastry separation axis",verticalKey,{ranges,modelHeight:extent[verticalKey],explosionDistance});
  return{scene,meshes,offsets,originals,verticalAxis,explosionDistance};
 },[gltf.scene]);
 const signal=()=>{if(signaled.current)return;signaled.current=true;requestAnimationFrame(()=>requestAnimationFrame(onReady))};
 useEffect(()=>{const anchors:Partial<Record<MeshName,Mesh>>={};prepared.meshes.forEach((mesh,name)=>{anchors[name]=mesh;mesh.onAfterRender=signal});bridge.pastry.current=anchors;prepared.scene.updateMatrixWorld(true);if(process.env.NODE_ENV==="development"){console.debug("[Masa] GLB is initialized; waiting for the first rendered mesh frame before revealing the experience.");const localBounds=new Box3(),worldBounds=new Box3(),worldPosition=new Vector3();console.group("Masa · raw baklava.glb transforms");expectedMeshes.forEach(name=>{const mesh=prepared.meshes.get(name)!,original=prepared.originals.get(name)!;mesh.geometry.computeBoundingBox();localBounds.copy(mesh.geometry.boundingBox!);worldBounds.setFromObject(mesh);mesh.getWorldPosition(worldPosition);console.log(name,{parent:mesh.parent?.name,localPosition:original.position.toArray(),worldPosition:worldPosition.toArray(),quaternion:original.quaternion.toArray(),scale:original.scale.toArray(),localBoundsCenter:localBounds.getCenter(new Vector3()).toArray(),worldBoundsCenter:worldBounds.getCenter(new Vector3()).toArray()})});console.groupEnd()}return()=>{bridge.pastry.current={};prepared.meshes.forEach(mesh=>{mesh.onAfterRender=()=>undefined;(Array.isArray(mesh.material)?mesh.material:[mesh.material]).forEach(material=>material.dispose())})}},[bridge,prepared]);
 useFrame((_,delta)=>{const group=root.current;if(!group||prepared.meshes.size!==expectedMeshes.length)return;signal();const p=bridge.progress.current.current,isMobile=size.width<720,pose=storyPose(p,isMobile),index=getInspectionIndex(p),inspection=index>=0?inspections[index]:null,local=inspectionLocal(p),focus=inspection?smooth(range(local,.04,.18))*(1-smooth(range(local,.82,.97))):0,master=debugMode.current==="raw"?0:explosionProgress(p),masterDelta=master-previousMaster.current,nextDirection=masterDelta>EPSILON?"opening":masterDelta<-EPSILON?"closing":direction.current;
  if(nextDirection!==direction.current){direction.current=nextDirection;directionStart.current=master;directionSnapshot.current={...currentOpenness.current};if(process.env.NODE_ENV==="development"&&debugMode.current)console.debug("Masa · direction changed",{direction:nextDirection,master:Number(master.toFixed(3)),from:directionSnapshot.current})}
  previousMaster.current=master;const canonical=direction.current==="opening"?openingTransforms(master):closingTransforms(master),directionTravel=Math.abs(master-directionStart.current),continuity=master===0||master===1?1:smooth(range(directionTravel,0,DIRECTION_BLEND)),debugRows:Record<string,{progress:number;offset:number}>={};
  prepared.meshes.forEach((mesh,name)=>{const original=prepared.originals.get(name)!,offset=prepared.offsets.get(name)!,pieceProgress=mix(directionSnapshot.current[name],canonical[name],continuity),verticalOffset=prepared.explosionDistance*DISTANCE_RATIO[name]*pieceProgress,active=debugMode.current!=="raw"&&inspection?.key===name,context=inspection&&debugMode.current!=="raw"?(active?1:.28):1;
   currentOpenness.current[name]=pieceProgress;
   offset.position.copy(prepared.verticalAxis).multiplyScalar(verticalOffset);offset.quaternion.identity();offset.scale.set(1,1,1);debugRows[name]={progress:Number(pieceProgress.toFixed(3)),offset:Number(verticalOffset.toFixed(4))};
   if(process.env.NODE_ENV==="development"&&!validatedClosed.current&&(p<EXPLOSION.start||p>=RECONSTRUCTION.end)){console.assert(mesh.position.equals(original.position)&&mesh.quaternion.equals(original.quaternion)&&mesh.scale.equals(original.scale),`${name} authored transform changed`);console.assert(offset.position.equals(new Vector3())&&offset.quaternion.equals(new Quaternion())&&offset.scale.equals(new Vector3(1,1,1)),`${name} offset group is not identity while closed`)}
   const materials=Array.isArray(mesh.material)?mesh.material:[mesh.material];materials.forEach((material,i)=>{material.opacity=context;material.depthWrite=context>.65;if(material instanceof MeshStandardMaterial){material.color.copy(original.colors[i]);material.emissive.set(active&&name==="Pistachio"?"#283318":"#000000");material.emissiveIntensity=active?.08*focus:0}});
  });
  if(process.env.NODE_ENV==="development"&&debugMode.current&&Math.abs(master-debugTick.current)>=.1){debugTick.current=master;const stageNumber=master<=0?0:master<=.2?1:master<=.4?2:master<=.6?3:master<=.8?4:5;console.info("Masa · explosion debug",{globalProgress:Number(master.toFixed(3)),stage:stageNumber,meshes:[...prepared.meshes.keys()]});console.table(debugRows)}
  if(process.env.NODE_ENV==="development"&&!validatedClosed.current&&(p<EXPLOSION.start||p>=RECONSTRUCTION.end)){validatedClosed.current=true;console.info("Masa · closed-state validation passed: all five mesh transforms are unchanged and all offset groups are identity.")}
  const px=bridge.progress.current.reduced?0:pointer.current.x,py=bridge.progress.current.reduced?0:pointer.current.y,settled=p>=.56&&p<.96;group.position.x=MathUtils.damp(group.position.x,pose.x,9,delta);group.position.y=MathUtils.damp(group.position.y,pose.y,9,delta);group.position.z=pose.z;group.rotation.y=MathUtils.damp(group.rotation.y,pose.rotationY+(settled?0:px*.025),8,delta);group.rotation.x=MathUtils.damp(group.rotation.x,pose.rotationX+(settled?0:py*.015),8,delta);group.scale.setScalar(pose.scale);
 });
 return <group ref={root}><primitive object={prepared.scene}/></group>;
}
useGLTF.preload("/Media/baklava.glb");
