"use client";
import {useGLTF} from "@react-three/drei";import {useFrame,useThree} from "@react-three/fiber";import {useEffect,useMemo,useRef} from "react";
import {Box3,Color,Euler,Group,Material,MathUtils,Mesh,MeshStandardMaterial,Quaternion,Vector3} from "three";
import {BAKLAVA_MODEL_URL} from "../modelAsset";import {anatomyInspectionLocal,anatomyInspections,getAnatomyInspectionIndex} from "../content/anatomy";import {expectedMeshes,MeshName} from "../content/story";import {range,smooth} from "../controllers/math";import {createRootPose,sampleStoryPose} from "../controllers/sceneTimeline";import type {ExperienceBridge} from "../experienceTypes";
type LogicalLayer=MeshName;type BaseTransform={scale:Vector3;colors:Color[]};type MotionSpec={start:number;end:number;c1:readonly[number,number,number];c2:readonly[number,number,number];to:readonly[number,number,number];rotation:readonly[number,number,number];focus:readonly[number,number,number];focusRotation:readonly[number,number,number]};type LayerRig={logical:LogicalLayer;mesh:Mesh;motion:Group;correction:Group;base:BaseTransform;originalSize:Vector3;correctedSize:Vector3;correctionFactors:Vector3;spec:MotionSpec;explodedQuaternion:Quaternion;focusQuaternion:Quaternion};
export const LAYER_MAPPING:Readonly<Record<LogicalLayer,MeshName>>={TopShell:"TopShell",UpperFilo:"LowerFilo",Pistachio:"Pistachio",LowerFilo:"UpperFilo",BaseShell:"BaseShell"};
const LAYERS:readonly LogicalLayer[]=["TopShell","UpperFilo","Pistachio","LowerFilo","BaseShell"];
const MOTION:Readonly<Record<LogicalLayer,MotionSpec>>={
 TopShell:{start:0,end:.38,c1:[.02,.16,.08],c2:[-.12,.42,.18],to:[-.16,.72,.25],rotation:[-.24,.2,-.13],focus:[-.035,.035,.16],focusRotation:[-.045,.06,.025]},
 UpperFilo:{start:.13,end:.53,c1:[-.025,.1,-.02],c2:[.12,.27,-.13],to:[.16,.38,-.16],rotation:[.12,-.17,.09],focus:[.04,.025,.14],focusRotation:[.035,-.055,-.02]},
 Pistachio:{start:.3,end:.68,c1:[0,.025,.035],c2:[-.035,.08,.13],to:[-.06,.13,.18],rotation:[-.045,.1,.035],focus:[.025,.015,.19],focusRotation:[-.025,.07,.015]},
 LowerFilo:{start:.46,end:.84,c1:[.02,-.09,-.025],c2:[-.12,-.28,-.12],to:[-.17,-.4,-.16],rotation:[-.12,.15,-.085],focus:[-.04,-.02,.14],focusRotation:[.035,.055,.02]},
 BaseShell:{start:.62,end:1,c1:[-.015,-.16,.06],c2:[.1,-.48,.16],to:[.15,-.76,.22],rotation:[.23,-.18,.14],focus:[.035,-.035,.16],focusRotation:[.05,-.05,-.025]},
};
const identity=new Quaternion(),tempPosition=new Vector3(),tempFocus=new Vector3(),tempQuaternion=new Quaternion(),tempEuler=new Euler(),workBox=new Box3(),workCenter=new Vector3();
const correction=(n:number)=>MathUtils.clamp(n,1,1.42),cubic=(a:number,b:number,c:number,t:number)=>{const u=1-t;return 3*u*u*t*a+3*u*t*t*b+t*t*t*c};
const phasedAmount=(p:number,openStart:number,openEnd:number,closeStart:number,closeEnd:number)=>p<openStart?0:p<openEnd?smooth(range(p,openStart,openEnd)):p<closeStart?1:p<closeEnd?1-smooth(range(p,closeStart,closeEnd)):0;
export function SingleBaklava({bridge,pointer,onReady}:{bridge:ExperienceBridge;pointer:React.MutableRefObject<{x:number;y:number}>;onReady:()=>void}){
 const gltf=useGLTF(BAKLAVA_MODEL_URL,false,true),root=useRef<Group>(null),validated=useRef(false),rootPose=useRef(createRootPose()),rootQuaternion=useRef(new Quaternion()),{size}=useThree();
 const prepared=useMemo(()=>{const scene=gltf.scene.clone(true),physical=new Map<MeshName,Mesh>();scene.traverse(child=>{if(!(child instanceof Mesh)||!expectedMeshes.includes(child.name as MeshName))return;const array=Array.isArray(child.material),source=array?child.material:[child.material],materials=source.map((material:Material)=>{const clone=material.clone();clone.transparent=true;return clone});child.material=array?materials:materials[0];child.castShadow=false;child.receiveShadow=false;child.geometry.computeBoundingBox();physical.set(child.name as MeshName,child)});const missing=expectedMeshes.filter(name=>!physical.has(name));if(missing.length||physical.size!==5)throw new Error(`Masa GLB mesh mismatch: ${missing.join(", ")||physical.size}`);scene.updateMatrixWorld(true);
  const dimensions=new Map<MeshName,Vector3>();physical.forEach((mesh,name)=>dimensions.set(name,new Box3().setFromObject(mesh).getSize(new Vector3())));const top=dimensions.get("TopShell")!,base=dimensions.get("BaseShell")!,shellAverage=new Vector3().addVectors(top,base).multiplyScalar(.5),minShell=Math.min(shellAverage.x,shellAverage.y,shellAverage.z),verticalAxis:"x"|"y"|"z"=minShell===shellAverage.x?"x":minShell===shellAverage.z?"z":"y",rigs=new Map<LogicalLayer,LayerRig>();
  LAYERS.forEach(logical=>{const mesh=physical.get(LAYER_MAPPING[logical])!,parent=mesh.parent;if(!parent)throw new Error(`Masa mesh has no parent: ${mesh.name}`);const originalSize=dimensions.get(LAYER_MAPPING[logical])!.clone(),filo=logical==="UpperFilo"||logical==="LowerFilo",factors=new Vector3(1,1,1);if(filo){if(verticalAxis!=="x")factors.x=correction(shellAverage.x*.94/originalSize.x);if(verticalAxis!=="y")factors.y=correction(shellAverage.y*.94/originalSize.y);if(verticalAxis!=="z")factors.z=correction(shellAverage.z*.94/originalSize.z)};workBox.setFromObject(mesh).getCenter(workCenter);parent.worldToLocal(workCenter);const motion=new Group(),footprint=new Group();motion.name=`${logical}Motion`;footprint.name=`${logical}FootprintCorrection`;motion.position.copy(workCenter);footprint.scale.set(1,1,1);parent.add(motion);motion.add(footprint);mesh.position.sub(workCenter);footprint.add(mesh);scene.updateMatrixWorld(true);const correctedSize=originalSize.clone().multiply(factors),materials=Array.isArray(mesh.material)?mesh.material:[mesh.material],baseTransform={scale:mesh.scale.clone(),colors:materials.map(material=>material instanceof MeshStandardMaterial?material.color.clone():new Color(1,1,1))},spec=MOTION[logical];rigs.set(logical,{logical,mesh,motion,correction:footprint,base:baseTransform,originalSize,correctedSize,correctionFactors:factors,spec,explodedQuaternion:new Quaternion().setFromEuler(new Euler(...spec.rotation)),focusQuaternion:new Quaternion().setFromEuler(new Euler(...spec.focusRotation))})});
  scene.updateMatrixWorld(true);const box=new Box3().setFromObject(scene),extent=box.getSize(new Vector3()),center=box.getCenter(new Vector3()),normalizer=1.32/Math.max(extent.x,extent.y,extent.z);scene.scale.setScalar(normalizer);scene.position.copy(center).multiplyScalar(-normalizer);return{scene,rigs,verticalAxis}},[gltf.scene]);
 useEffect(()=>{const anchors:Partial<Record<LogicalLayer,Mesh>>={};prepared.rigs.forEach((rig,logical)=>anchors[logical]=rig.mesh);bridge.pastry.current=anchors;prepared.scene.updateMatrixWorld(true);if(process.env.NODE_ENV==="development"){console.group("Masa Â· logical layer mapping");LAYERS.forEach(logical=>console.info(`${logical} -> ${LAYER_MAPPING[logical]}`));console.groupEnd();console.group(`Masa · anatomy footprint; ${String(prepared.verticalAxis).toUpperCase()} thickness unchanged`);prepared.rigs.forEach(rig=>console.info(rig.logical,{meshName:rig.mesh.name,originalSize:rig.originalSize.toArray(),correctedSize:rig.correctedSize.toArray(),correctionFactors:rig.correctionFactors.toArray(),meshBaseScale:rig.base.scale.toArray()}));console.groupEnd()}onReady();return()=>{bridge.pastry.current={};prepared.rigs.forEach(rig=>(Array.isArray(rig.mesh.material)?rig.mesh.material:[rig.mesh.material]).forEach(material=>material.dispose()))}},[bridge,onReady,prepared]);
 useFrame(()=>{const group=root.current;if(!group)return;const p=bridge.progress.current.current,mobile=size.width<720,pose=sampleStoryPose(p,mobile,rootPose.current),shellAmount=phasedAmount(p,.58,.625,.93,.96),internalAmount=phasedAmount(p,.615,.675,.89,.93),footprintAmount=phasedAmount(p,.625,.67,.89,.925),index=getAnatomyInspectionIndex(p),inspection=index>=0?anatomyInspections[index]:null,local=inspection?anatomyInspectionLocal(p):0,focus=inspection?smooth(range(local,.05,.2))*(1-smooth(range(local,.8,.96))):0,motionScale=mobile?.82:1;tempEuler.set(pose.rotationX,pose.rotationY,pose.rotationZ);rootQuaternion.current.setFromEuler(tempEuler);group.position.set(pose.x,pose.y,pose.z);group.quaternion.copy(rootQuaternion.current);group.scale.setScalar(pose.scale);
  prepared.rigs.forEach(rig=>{const amount=rig.logical==="TopShell"||rig.logical==="BaseShell"?shellAmount:internalAmount,active=inspection?.layers.includes(rig.logical)??false,focusAmount=active?focus:0,s=rig.spec;tempPosition.set(cubic(s.c1[0],s.c2[0],s.to[0],amount)*motionScale,cubic(s.c1[1],s.c2[1],s.to[1],amount),cubic(s.c1[2],s.c2[2],s.to[2],amount)*(mobile?.72:1));tempFocus.set(s.focus[0],s.focus[1],s.focus[2]*(mobile?.72:1)).multiplyScalar(focusAmount);rig.motion.position.copy(tempPosition).add(tempFocus);rig.motion.quaternion.slerpQuaternions(identity,rig.explodedQuaternion,amount);tempQuaternion.slerpQuaternions(identity,rig.focusQuaternion,focusAmount);rig.motion.quaternion.multiply(tempQuaternion);rig.correction.scale.set(MathUtils.lerp(1,rig.correctionFactors.x,footprintAmount),MathUtils.lerp(1,rig.correctionFactors.y,footprintAmount),MathUtils.lerp(1,rig.correctionFactors.z,footprintAmount));rig.mesh.scale.copy(rig.base.scale);const emphasis=inspection?(active?1:.64):1,materials=Array.isArray(rig.mesh.material)?rig.mesh.material:[rig.mesh.material];materials.forEach((material,i)=>{material.opacity=emphasis;material.depthWrite=emphasis>.7;if(material instanceof MeshStandardMaterial){material.color.copy(rig.base.colors[i]);material.emissive.set(active&&rig.logical==="Pistachio"?"#283318":"#000000");material.emissiveIntensity=active?.07*focus:0}})});
  if(process.env.NODE_ENV==="development"&&!validated.current&&p>=.965){validated.current=true;prepared.rigs.forEach(rig=>{console.assert(rig.mesh.scale.equals(rig.base.scale),`${rig.logical}: mesh scale changed`);console.assert(Math.abs(rig.correction.scale.x-1)<1e-6&&Math.abs(rig.correction.scale.y-1)<1e-6&&Math.abs(rig.correction.scale.z-1)<1e-6,`${rig.logical}: assembled correction drift`);console.assert(rig.motion.position.lengthSq()<1e-10,`${rig.logical}: base position mismatch`);console.assert(Math.abs(rig.motion.quaternion.dot(identity))>.99999,`${rig.logical}: base rotation mismatch`)})}if(!bridge.progress.current.reduced&&shellAmount===0&&internalAmount===0){group.position.x+=pointer.current.x*.018;group.position.y+=pointer.current.y*.01}});
 const initial=sampleStoryPose(0,size.width<720,rootPose.current);return <group ref={root} name="BaklavaRoot" position={[initial.x,initial.y,initial.z]} rotation={[initial.rotationX,initial.rotationY,initial.rotationZ]} scale={initial.scale}><primitive object={prepared.scene}/></group>;
}
