"use client";

import {useGLTF} from "@react-three/drei";
import {useFrame,useThree} from "@react-three/fiber";
import {useEffect,useMemo,useRef} from "react";
import {Box3,Color,Euler,Group,Material,MathUtils,Mesh,MeshStandardMaterial,Quaternion,Vector3} from "three";
import {BAKLAVA_MODEL_URL} from "../modelAsset";
import {anatomyInspectionLocal,anatomyInspections,getAnatomyInspectionIndex} from "../content/anatomy";
import {expectedMeshes,MeshName} from "../content/story";
import {range,smooth} from "../controllers/math";
import {createRootPose,sampleStoryPose} from "../controllers/sceneTimeline";
import type {ExperienceBridge} from "../experienceTypes";

type LogicalLayer=MeshName;
type Axis="x"|"y"|"z";
type OriginalTransform={position:Vector3;quaternion:Quaternion;scale:Vector3;colors:Color[]};
type MotionSpec={c1:readonly[number,number,number];c2:readonly[number,number,number];to:readonly[number,number,number];rotation:readonly[number,number,number];focus:readonly[number,number,number];focusRotation:readonly[number,number,number]};
type LayerRig={logical:LogicalLayer;mesh:Mesh;motion:Group;footprint:Group;original:OriginalTransform;assembledSize:Vector3;anatomySize:Vector3;anatomyScale:Vector3;spec:MotionSpec;anatomyQuaternion:Quaternion;focusQuaternion:Quaternion;releaseOffset:Vector3;anatomyPosition:Vector3};

export const LAYER_MAPPING:Readonly<Record<LogicalLayer,MeshName>>={TopShell:"TopShell",UpperFilo:"LowerFilo",Pistachio:"Pistachio",LowerFilo:"UpperFilo",BaseShell:"BaseShell"};
const LAYERS:readonly LogicalLayer[]=["TopShell","UpperFilo","Pistachio","LowerFilo","BaseShell"];
const MOTION:Readonly<Record<LogicalLayer,MotionSpec>>={
 TopShell:{c1:[.015,.15,.04],c2:[-.055,.41,.1],to:[-.08,.58,.14],rotation:[-.15,.13,-.075],focus:[-.025,.025,.1],focusRotation:[-.035,.045,.018]},
 UpperFilo:{c1:[-.01,.034,-.005],c2:[.04,.20,-.055],to:[.07,.34,-.08],rotation:[.07,-.1,.045],focus:[.028,.014,.085],focusRotation:[.022,-.038,-.012]},
 Pistachio:{c1:[0,.006,.018],c2:[-.012,.02,.055],to:[-.02,.02,.075],rotation:[-.022,.045,.014],focus:[.012,.006,.1],focusRotation:[-.014,.04,.008]},
 LowerFilo:{c1:[.01,-.033,-.005],c2:[-.04,-.20,-.055],to:[-.07,-.34,-.08],rotation:[-.07,.1,-.045],focus:[-.028,-.014,.085],focusRotation:[.022,.038,.012]},
 BaseShell:{c1:[-.015,-.15,.035],c2:[.055,-.41,.095],to:[.08,-.58,.13],rotation:[.15,-.12,.075],focus:[.025,-.025,.1],focusRotation:[.035,-.04,-.018]},
};
const identity=new Quaternion(),tempPosition=new Vector3(),tempFocus=new Vector3(),tempQuaternion=new Quaternion(),tempEuler=new Euler();
const correction=(value:number)=>MathUtils.clamp(value,1,1.42);
const SHELL_PARTIAL=.44;
const UPPER_FILO_RELEASE=.16;
const LOWER_FILO_RELEASE=.15;
const PISTACHIO_ANATOMY_SCALE=Object.freeze({x:1.28,y:1.18,z:1.28});
const cubic=(a:number,b:number,c:number,t:number)=>{const u=1-t;return 3*u*u*t*a+3*u*t*t*b+t*t*t*c};
const phasedAmount=(p:number,openStart:number,openEnd:number,closeStart:number,closeEnd:number)=>p<openStart?0:p<openEnd?smooth(range(p,openStart,openEnd)):p<closeStart?1:p<closeEnd?1-smooth(range(p,closeStart,closeEnd)):0;
const equalsVector=(a:Vector3,b:Vector3)=>a.distanceToSquared(b)<1e-12;
const equalsQuaternion=(a:Quaternion,b:Quaternion)=>Math.abs(a.dot(b))>1-1e-10;

export function SingleBaklava({bridge,onReady}:{bridge:ExperienceBridge;onReady:()=>void}){
 const gltf=useGLTF(BAKLAVA_MODEL_URL,false,true),root=useRef<Group>(null),validated=useRef(false),rootPose=useRef(createRootPose()),rootQuaternion=useRef(new Quaternion()),{size}=useThree();
 const prepared=useMemo(()=>{
  const scene=gltf.scene.clone(true),physical=new Map<MeshName,Mesh>();
  scene.traverse(child=>{if(!(child instanceof Mesh)||!expectedMeshes.includes(child.name as MeshName))return;const array=Array.isArray(child.material),source=array?child.material:[child.material],materials=source.map((material:Material)=>{const clone=material.clone();clone.transparent=true;return clone});child.material=array?materials:materials[0];child.castShadow=false;child.receiveShadow=false;child.geometry.computeBoundingBox();physical.set(child.name as MeshName,child)});
  const missing=expectedMeshes.filter(name=>!physical.has(name));if(missing.length||physical.size!==5)throw new Error(`Masa GLB mesh mismatch: ${missing.join(", ")||physical.size}`);
  scene.updateMatrixWorld(true);
  const dimensions=new Map<MeshName,Vector3>();physical.forEach((mesh,name)=>dimensions.set(name,new Box3().setFromObject(mesh).getSize(new Vector3())));
  const top=dimensions.get("TopShell")!,base=dimensions.get("BaseShell")!,shellAverage=new Vector3().addVectors(top,base).multiplyScalar(.5),minimum=Math.min(shellAverage.x,shellAverage.y,shellAverage.z),verticalAxis:Axis=minimum===shellAverage.x?"x":minimum===shellAverage.z?"z":"y",rigs=new Map<LogicalLayer,LayerRig>();
  LAYERS.forEach(logical=>{const mesh=physical.get(LAYER_MAPPING[logical])!,parent=mesh.parent;if(!parent)throw new Error(`Masa mesh has no parent: ${mesh.name}`);const materials=Array.isArray(mesh.material)?mesh.material:[mesh.material],original={position:mesh.position.clone(),quaternion:mesh.quaternion.clone(),scale:mesh.scale.clone(),colors:materials.map(material=>material instanceof MeshStandardMaterial?material.color.clone():new Color(1,1,1))},assembledSize=dimensions.get(LAYER_MAPPING[logical])!.clone(),anatomyScale=new Vector3(1,1,1),filo=logical==="UpperFilo"||logical==="LowerFilo";if(filo){(['x','y','z'] as Axis[]).forEach(axis=>{if(axis!==verticalAxis)anatomyScale[axis]=correction(shellAverage[axis]*.94/assembledSize[axis])})}const motion=new Group(),footprint=new Group();motion.name=`${logical}Motion`;footprint.name=`${logical}AnatomyFootprint`;parent.add(motion);motion.add(footprint);footprint.add(mesh);mesh.position.copy(original.position);mesh.quaternion.copy(original.quaternion);mesh.scale.copy(original.scale);const spec=MOTION[logical];rigs.set(logical,{logical,mesh,motion,footprint,original,assembledSize,anatomySize:assembledSize.clone().multiply(anatomyScale),anatomyScale,spec,anatomyQuaternion:new Quaternion().setFromEuler(new Euler(...spec.rotation)),focusQuaternion:new Quaternion().setFromEuler(new Euler(...spec.focusRotation)),releaseOffset:new Vector3(),anatomyPosition:new Vector3()})});
  const pistachioRig=rigs.get("Pistachio")!;pistachioRig.anatomyScale.set(PISTACHIO_ANATOMY_SCALE.x,PISTACHIO_ANATOMY_SCALE.y,PISTACHIO_ANATOMY_SCALE.z);pistachioRig.anatomySize.copy(pistachioRig.assembledSize).multiply(pistachioRig.anatomyScale);
  rigs.forEach((rig)=>{const toX=rig.spec.to[0],toY=rig.spec.to[1],toZ=rig.spec.to[2],toAxis=verticalAxis==="x"?toX:verticalAxis==="y"?toY:toZ,direction=Math.sign(toAxis);let dist=Math.abs(toAxis)*.32;if(rig.logical==="UpperFilo")dist=UPPER_FILO_RELEASE;else if(rig.logical==="LowerFilo")dist=LOWER_FILO_RELEASE;rig.releaseOffset.set(0,0,0);rig.releaseOffset[verticalAxis]=direction*dist;rig.anatomyPosition.set(toX,toY,toZ)});
  scene.updateMatrixWorld(true);const box=new Box3().setFromObject(scene),extent=box.getSize(new Vector3()),center=box.getCenter(new Vector3()),normalizer=1.32/Math.max(extent.x,extent.y,extent.z);scene.scale.setScalar(normalizer);scene.position.copy(center).multiplyScalar(-normalizer);return{scene,rigs,verticalAxis};
 },[gltf.scene]);
 useEffect(()=>{const anchors:Partial<Record<LogicalLayer,Mesh>>={};prepared.rigs.forEach((rig,logical)=>anchors[logical]=rig.mesh);bridge.pastry.current=anchors;prepared.scene.updateMatrixWorld(true);if(process.env.NODE_ENV==="development"){console.group("Masa · logical layer mapping");LAYERS.forEach(logical=>console.info(`${logical} -> ${LAYER_MAPPING[logical]}`));console.groupEnd();console.group(`Masa · transforms and dimensions; ${prepared.verticalAxis.toUpperCase()} is vertical`);prepared.rigs.forEach(rig=>console.info(rig.logical,{meshName:rig.mesh.name,originalTransform:{position:rig.original.position.toArray(),quaternion:rig.original.quaternion.toArray(),scale:rig.original.scale.toArray()},assembledTransform:{position:rig.mesh.position.toArray(),quaternion:rig.mesh.quaternion.toArray(),scale:rig.mesh.scale.toArray()},anatomyTransform:{offset:rig.spec.to,rotation:rig.spec.rotation,scale:rig.anatomyScale.toArray()},assembledDimensions:rig.assembledSize.toArray(),anatomyDimensions:rig.anatomySize.toArray(),closedEqualsOriginal:equalsVector(rig.mesh.position,rig.original.position)&&equalsQuaternion(rig.mesh.quaternion,rig.original.quaternion)&&equalsVector(rig.mesh.scale,rig.original.scale)}));console.groupEnd();console.group("Masa · filo three states (RELEASE)");(["UpperFilo","LowerFilo"] as LogicalLayer[]).forEach(logical=>{const rig=prepared.rigs.get(logical)!;console.info(`${logical} (${rig.mesh.name}):`,{ASSEMBLED_position:rig.original.position.toArray(),RELEASE_position:rig.releaseOffset.toArray(),ANATOMY_position:rig.anatomyPosition.toArray(),ASSEMBLED_scale:rig.original.scale.toArray(),RELEASE_scale:rig.original.scale.toArray(),ANATOMY_scale:rig.anatomyScale.toArray(),releaseOffsetAlong:prepared.verticalAxis});console.assert(equalsVector(rig.original.scale,rig.original.scale),`${rig.logical}: ASSEMBLED scale must equal RELEASE scale`)});console.groupEnd()}onReady();return()=>{bridge.pastry.current={};prepared.rigs.forEach(rig=>(Array.isArray(rig.mesh.material)?rig.mesh.material:[rig.mesh.material]).forEach(material=>material.dispose()))}},[bridge,onReady,prepared]);
 useFrame(()=>{const group=root.current;if(!group)return;const p=bridge.progress.current.current,mobile=size.width<720,pose=sampleStoryPose(p,mobile,rootPose.current),shellA=phasedAmount(p,.58,.612,.925,.955),shellB=phasedAmount(p,.622,.68,.90,.925),shellAmount=shellA*SHELL_PARTIAL+shellB*(1-SHELL_PARTIAL),internalAmount=phasedAmount(p,.63,.68,.89,.92),footprintAmount=phasedAmount(p,.63,.665,.905,.925),filoReleaseUpper=phasedAmount(p,.592,.61,.928,.942),filoReleaseLower=phasedAmount(p,.602,.622,.924,.944),filoExpandAmount=phasedAmount(p,.63,.665,.905,.925),filoSettleAmount=phasedAmount(p,.65,.68,.89,.905),index=getAnatomyInspectionIndex(p),inspection=index>=0?anatomyInspections[index]:null,local=inspection?anatomyInspectionLocal(p):0,focus=inspection?smooth(range(local,.05,.2))*(1-smooth(range(local,.8,.96))):0,motionScale=mobile?.86:1;tempEuler.set(pose.rotationX,pose.rotationY,pose.rotationZ);rootQuaternion.current.setFromEuler(tempEuler);group.position.set(pose.x,pose.y,pose.z);group.quaternion.copy(rootQuaternion.current);group.scale.setScalar(pose.scale);
  prepared.rigs.forEach(rig=>{const isFilo=rig.logical==="UpperFilo"||rig.logical==="LowerFilo",active=inspection?.layers.includes(rig.logical)??false,focusAmount=active?focus:0,s=rig.spec;if(isFilo){const rx=rig.releaseOffset.x*motionScale,ry=rig.releaseOffset.y*(mobile?.88:1),rz=rig.releaseOffset.z*(mobile?.72:1),ax=rig.anatomyPosition.x*motionScale,ay=rig.anatomyPosition.y*(mobile?.88:1),az=rig.anatomyPosition.z*(mobile?.72:1),releaseAmount=rig.logical==="UpperFilo"?filoReleaseUpper:filoReleaseLower;if(filoSettleAmount>0){tempPosition.set(rx+(ax-rx)*filoSettleAmount,ry+(ay-ry)*filoSettleAmount,rz+(az-rz)*filoSettleAmount)}else{tempPosition.set(rx*releaseAmount,ry*releaseAmount,rz*releaseAmount)}rig.motion.quaternion.slerpQuaternions(identity,rig.anatomyQuaternion,filoSettleAmount);rig.footprint.scale.set(MathUtils.lerp(1,rig.anatomyScale.x,filoExpandAmount),MathUtils.lerp(1,rig.anatomyScale.y,filoExpandAmount),MathUtils.lerp(1,rig.anatomyScale.z,filoExpandAmount))}else{const amount=rig.logical==="TopShell"||rig.logical==="BaseShell"?shellAmount:internalAmount,sizeAmount=rig.logical==="Pistachio"?internalAmount:footprintAmount;tempPosition.set(cubic(s.c1[0],s.c2[0],s.to[0],amount)*motionScale,cubic(s.c1[1],s.c2[1],s.to[1],amount)*(mobile?.88:1),cubic(s.c1[2],s.c2[2],s.to[2],amount)*(mobile?.72:1));rig.motion.quaternion.slerpQuaternions(identity,rig.anatomyQuaternion,amount);rig.footprint.scale.set(MathUtils.lerp(1,rig.anatomyScale.x,sizeAmount),MathUtils.lerp(1,rig.anatomyScale.y,sizeAmount),MathUtils.lerp(1,rig.anatomyScale.z,sizeAmount))}tempFocus.set(s.focus[0],s.focus[1],s.focus[2]*(mobile?.72:1)).multiplyScalar(focusAmount);rig.motion.position.copy(tempPosition).add(tempFocus);tempQuaternion.slerpQuaternions(identity,rig.focusQuaternion,focusAmount);rig.motion.quaternion.multiply(tempQuaternion);rig.mesh.position.copy(rig.original.position);rig.mesh.quaternion.copy(rig.original.quaternion);rig.mesh.scale.copy(rig.original.scale);const emphasis=inspection?(active?1:.72):1,materials=Array.isArray(rig.mesh.material)?rig.mesh.material:[rig.mesh.material];materials.forEach((material,i)=>{material.opacity=emphasis;material.depthWrite=emphasis>.7;if(material instanceof MeshStandardMaterial){material.color.copy(rig.original.colors[i]);material.emissive.set(active&&rig.logical==="Pistachio"?"#283318":"#000000");material.emissiveIntensity=active?.055*focus:0}})});
  if(process.env.NODE_ENV==="development"){const anatomyStable=p>=.685&&p<.89;if(anatomyStable)prepared.rigs.forEach(rig=>{if(rig.logical==="UpperFilo"||rig.logical==="LowerFilo"){console.assert(equalsVector(rig.footprint.scale,rig.anatomyScale),`${rig.logical}: anatomy scale changed during focus`);console.assert(filoExpandAmount>=.98,`${rig.logical}: expand not complete during anatomy stable`);console.assert(filoSettleAmount>=.98,`${rig.logical}: settle not complete during anatomy stable`)}});if(!validated.current&&p>=.965){validated.current=true;prepared.rigs.forEach(rig=>{console.assert(equalsVector(rig.mesh.position,rig.original.position),`${rig.logical}: original position drift`);console.assert(equalsQuaternion(rig.mesh.quaternion,rig.original.quaternion),`${rig.logical}: original quaternion drift`);console.assert(equalsVector(rig.mesh.scale,rig.original.scale),`${rig.logical}: original scale drift`);console.assert(rig.motion.position.lengthSq()<1e-12,`${rig.logical}: closed motion offset`);console.assert(equalsQuaternion(rig.motion.quaternion,identity),`${rig.logical}: closed motion rotation`);console.assert(equalsVector(rig.footprint.scale,tempPosition.set(1,1,1)),`${rig.logical}: closed anatomy scale`)})}}
 });
 const initial=sampleStoryPose(0,size.width<720,rootPose.current);return <group ref={root} name="BaklavaRoot" position={[initial.x,initial.y,initial.z]} rotation={[initial.rotationX,initial.rotationY,initial.rotationZ]} scale={initial.scale}><primitive object={prepared.scene}/></group>;
}
