"use client";
import { useEffect, useRef } from "react";
import { anatomyLabels, getInspectionIndex } from "./content/story";
import { range, smooth } from "./controllers/math";
import type { ExperienceBridge } from "./experienceTypes";
export function ConnectorOverlay({ bridge }: { bridge: ExperienceBridge }) {
  const root = useRef<HTMLDivElement>(null);
  useEffect(() => { const element = root.current; if (!element) return; const groups = anatomyLabels.map((l) => element.querySelector<SVGGElement>(`[data-connector="${l.key}"]`)); const copies = anatomyLabels.map((l) => element.querySelector<HTMLElement>(`[data-label="${l.key}"]`)); const paths = groups.map((g) => g?.querySelector<SVGPathElement>("path")); let raf = 0; const draw = () => { const p = bridge.progress.current.current; const activeIndex = getInspectionIndex(p); const mobile = innerWidth < 720; anatomyLabels.forEach((label, index) => { const group = groups[index], copy = copies[index], path = paths[index]; const anchor = bridge.anchors.current[label.key]; if (!group || !copy || !path || !anchor || index !== activeIndex) { if (group) group.style.opacity = "0"; if (copy) copy.style.setProperty("--label-show", "0"); return; } const local = (p - (.61 + index * (.245 / 13))) / (.245 / 13); const reveal = smooth(range(local, .04, .28)) * (1 - smooth(range(local, .78, .98))); const side = index % 2 ? 1 : -1; const targetX = mobile ? (side < 0 ? 22 : innerWidth - 22) : (side < 0 ? innerWidth * .18 : innerWidth * .82); const verticalBias = mobile ? (index < 6 ? 92 : innerHeight - 120) : Math.min(innerHeight - 100, Math.max(110, anchor.y + (index % 3 - 1) * 34)); const elbowX = anchor.x + (targetX - anchor.x) * .46; path.setAttribute("d", `M ${anchor.x.toFixed(1)} ${anchor.y.toFixed(1)} L ${elbowX.toFixed(1)} ${verticalBias.toFixed(1)} L ${targetX.toFixed(1)} ${verticalBias.toFixed(1)}`); path.style.strokeDashoffset = String(1 - reveal); group.style.opacity = String(reveal); copy.style.setProperty("--label-x", `${targetX}px`); copy.style.setProperty("--label-y", `${verticalBias}px`); copy.style.setProperty("--label-show", String(smooth(range(reveal, .42, 1)))); copy.dataset.side = side < 0 ? "left" : "right"; }); raf = requestAnimationFrame(draw); }; raf = requestAnimationFrame(draw); return () => cancelAnimationFrame(raf); }, [bridge]);
  return <div ref={root} className="connector-overlay"><svg aria-hidden="true">{anatomyLabels.map((label) => <g key={label.key} data-connector={label.key}><path pathLength="1" /></g>)}</svg>{anatomyLabels.map((label, index) => <div className="anatomy-label" data-label={label.key} key={label.key}><b>{String(index + 1).padStart(2, "0")} / 13</b><span>{label.title}</span><small>{label.body}</small></div>)}</div>;
}
