"use client";
import {Canvas,useFrame,useThree} from "@react-three/fiber";
import {Component,ReactNode,Suspense,useEffect,useRef} from "react";
import {ACESFilmicToneMapping,AdditiveBlending,AmbientLight,Box3,DirectionalLight,DoubleSide,MathUtils,Mesh,PCFSoftShadowMap,PerspectiveCamera,ShaderMaterial,SpotLight,SRGBColorSpace,Vector3} from "three";
import {anatomyInspections,getAnatomyInspectionIndex} from "./content/anatomy";
import {CINEMATIC_CAMERA,getResponsiveProfile} from "./content/responsiveScenes";
import {getWidthMode,MODE_CONFIG} from "./content/deviceConfig";
import {range,smooth} from "./controllers/math";
import {createRootPose,EXPLOSION,PRE_ANATOMY,RECONSTRUCTION,sampleStoryPose,STORY_SCENES} from "./controllers/sceneTimeline";
import type {ExperienceBridge} from "./experienceTypes";
import {SingleBaklava} from "./models/SingleBaklava";
import {projectWorldToScreen} from "./three/projection";
const target=new Vector3(),selectedWorld=new Vector3(),bounds=new Box3(),anchorV=new Vector3(),leftWorld=new Vector3(),rightWorld=new Vector3();
const edgeCache=new WeakMap<Mesh,{left:Vector3;right:Vector3}>();
function geometryEdges(mesh:Mesh){
 const cached=edgeCache.get(mesh);if(cached)return cached;
 mesh.geometry.boundingBox??mesh.geometry.computeBoundingBox();
 const box=mesh.geometry.boundingBox!,position=mesh.geometry.attributes.position,targetY=MathUtils.lerp(box.min.y,box.max.y,.5),band=Math.max(.001,(box.max.y-box.min.y)*.22),step=Math.max(1,Math.floor(position.count/3200));
 const left=new Vector3(box.min.x,targetY,(box.min.z+box.max.z)*.5),right=new Vector3(box.max.x,targetY,(box.min.z+box.max.z)*.5);let min=Infinity,max=-Infinity;
 for(let vertex=0;vertex<position.count;vertex+=step){anchorV.fromBufferAttribute(position,vertex);if(Math.abs(anchorV.y-targetY)>band)continue;if(anchorV.x<min){min=anchorV.x;left.copy(anchorV)}if(anchorV.x>max){max=anchorV.x;right.copy(anchorV)}}
 const result=leftWorld.copy(left).applyMatrix4(mesh.matrixWorld).x<=rightWorld.copy(right).applyMatrix4(mesh.matrixWorld).x?{left,right}:{left:right,right:left};edgeCache.set(mesh,result);return result;
}
class CanvasBoundary extends Component<{children:ReactNode;onError:()=>void},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return{failed:true}}componentDidCatch(){this.props.onError()}render(){return this.state.failed?null:this.props.children}}
function SpotlightBeam({bridge}:{bridge:ExperienceBridge}){const beam=useRef<Mesh>(null),material=useRef<ShaderMaterial>(null),{size}=useThree();useFrame(()=>{const p=bridge.progress.current.current,story=smooth(range(p,.035,.16)),mobile=getWidthMode(size.width)==="mobile";if(material.current)material.current.uniforms.uOpacity.value=(1-story)*.075;if(beam.current){beam.current.position.set(mobile?0:.4,2.2,mobile?1.1:1.28);beam.current.rotation.x=-.34;beam.current.scale.set(mobile?.84:1,mobile?1.02:1,mobile?.84:1)}});return <mesh ref={beam} position={[.4,2.2,1.28]} rotation={[-.34,0,0]} renderOrder={1}><coneGeometry args={[1.02,4.25,64,1,true]}/><shaderMaterial ref={material} transparent depthWrite={false} side={DoubleSide} blending={AdditiveBlending} uniforms={{uColor:{value:new Vector3(0.88,0.7,0.42)},uOpacity:{value:.075}}} vertexShader={'varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}'.replace(/\n/g,"")} fragmentShader={'uniform vec3 uColor;uniform float uOpacity;varying vec2 vUv;void main(){float edge=pow(max(0.0,sin(vUv.x*3.14159265)),0.7);float fade=smoothstep(0.02,0.28,vUv.y)*(1.0-smoothstep(0.72,1.0,vUv.y));gl_FragColor=vec4(uColor,uOpacity*edge*fade);}'.replace(/\n/g,"")}/></mesh>}
function Director({bridge,heroSpot,ambientLight,keyLight,fillLight,rimLight}:{bridge:ExperienceBridge;heroSpot:React.RefObject<SpotLight|null>;ambientLight:React.RefObject<AmbientLight|null>;keyLight:React.RefObject<DirectionalLight|null>;fillLight:React.RefObject<DirectionalLight|null>;rimLight:React.RefObject<DirectionalLight|null>}){
 const {camera,size,scene,pointer,gl}=useThree(),pose=useRef(createRootPose()),lastMode=useRef("");
useFrame((state,delta)=>{
   const safeDelta=Math.min(Math.max(delta,0),0.05),profile=getResponsiveProfile(size.width,size.height),mode=profile.mode,mobile=mode==="mobile",cfg=MODE_CONFIG[mode],store=bridge.progress.current;store.current=MathUtils.damp(store.current,store.target,cfg.camera.stageDamp,safeDelta);
   store.velocity=MathUtils.damp(store.velocity,0,8,safeDelta);
   const p=store.current,cinema=CINEMATIC_CAMERA[mode],rootPose=sampleStoryPose(p,size.width,size.height,pose.current),anatomy=smooth(range(p,PRE_ANATOMY.start,EXPLOSION.end)),index=getAnatomyInspectionIndex(p),profileKey=`${profile.kind}:${Math.round(size.width/20)}:${Math.round(size.height/20)}`;
   if(lastMode.current!==profileKey&&camera instanceof PerspectiveCamera){lastMode.current=profileKey;camera.fov=profile.fov;camera.near=.1;camera.far=100;camera.updateProjectionMatrix()}
   const hero=smooth(range(p,.008,STORY_SCENES.hero.revealEnd))*(1-smooth(range(p,.125,STORY_SCENES.hero.end))),history=smooth(range(p,STORY_SCENES.history.start,.17))*(1-smooth(range(p,.265,STORY_SCENES.history.end))),craft=smooth(range(p,STORY_SCENES.craft.start,.31))*(1-smooth(range(p,.42,STORY_SCENES.craft.end))),preparation=smooth(range(p,STORY_SCENES.preparation.start,.465))*(1-smooth(range(p,.5,STORY_SCENES.preparation.end))),quiet=Math.abs(store.velocity)<.00035&&((p<.49)||(p>.965));
   const push=hero*cinema.heroPush*.45+craft*cinema.craftPush*.7-history*.12;
   const idle=store.reduced?0:(quiet?Math.sin(state.clock.elapsedTime*.45)*cinema.idle*.45:0),inertia=store.reduced?0:MathUtils.clamp(store.velocity*4,-.015,.015),pointerWeight=(p<.49||p>.96)?cinema.pointer:0;
   let cameraX=rootPose.x*cfg.camera.posXFactor+pointer.x*pointerWeight+inertia,cameraY=.06+rootPose.y*cfg.camera.posYFactor+pointer.y*pointerWeight*.55+idle,cameraZ=profile.cameraZ-rootPose.z*cfg.camera.posZFactor-push,targetX=rootPose.x*cfg.camera.targetXFactor+pointer.x*pointerWeight*.35,targetY=rootPose.y*cfg.camera.targetYFactor+idle*.5;
   let cameraLocked=false;
   if(p>=PRE_ANATOMY.start&&p<RECONSTRUCTION.end){const fit=smooth(range(p,cfg.explode.start,cfg.explode.end));cameraX=0;cameraY=cfg.camera.anatomyYMode==="profile"?profile.anatomyCenterY*.28:0;cameraZ=profile.anatomyCameraZ+(cfg.camera.anatomyYMode==="profile"?cfg.camera.anatomyOffsetZ:fit*cfg.camera.anatomyOffsetZ);targetX=0;targetY=cfg.camera.anatomyTargetY==="profile"?profile.anatomyCenterY:cfg.camera.anatomyTargetY;if(cfg.camera.lockCameraInAnatomy&&p>=cfg.explode.end)cameraLocked=true}
   if(index>=0&&!mobile){const object=bridge.pastry.current[anatomyInspections[index].layers[0]];if(object instanceof Mesh){object.geometry.boundingBox??object.geometry.computeBoundingBox();if(object.geometry.boundingBox){bounds.copy(object.geometry.boundingBox).applyMatrix4(object.matrixWorld).getCenter(selectedWorld);targetY=MathUtils.clamp(selectedWorld.y*.18,-.28,.28);cameraZ-=.18}}}
   if(cameraLocked){camera.position.set(cameraX,cameraY,cameraZ)}else{camera.position.x=MathUtils.damp(camera.position.x,cameraX,cfg.camera.cameraDamp,safeDelta);camera.position.y=MathUtils.damp(camera.position.y,cameraY,cfg.camera.cameraDamp,safeDelta);camera.position.z=MathUtils.damp(camera.position.z,cameraZ,cfg.camera.cameraDamp,safeDelta)}target.set(targetX,targetY,0);camera.lookAt(target);camera.updateMatrixWorld();bridge.camera.current=camera;
   if(index>=0){const item=anatomyInspections[index],canvasRect=gl.domElement.getBoundingClientRect(),rect={left:canvasRect.left,top:canvasRect.top,width:canvasRect.width,height:canvasRect.height};item.layers.forEach(layer=>{const object=bridge.pastry.current[layer];if(object instanceof Mesh&&object.geometry.boundingBox){object.updateWorldMatrix(true,false);const local=object.geometry.boundingBox,centerWorld=local.getCenter(selectedWorld).applyMatrix4(object.matrixWorld),center=projectWorldToScreen(centerWorld,camera,rect);let edge=center,side=item.station;if(mobile){const candidates=geometryEdges(object);leftWorld.copy(candidates.left).applyMatrix4(object.matrixWorld);rightWorld.copy(candidates.right).applyMatrix4(object.matrixWorld);const left=projectWorldToScreen(leftWorld,camera,rect),right=projectWorldToScreen(rightWorld,camera,rect),margin=MathUtils.clamp(size.width*cfg.connector.marginOf,12,18),labelWidth=MathUtils.clamp(size.width*cfg.connector.labelWidthOf,108,118),leftGap=left.x-(margin+labelWidth),rightGap=(size.width-margin-labelWidth)-right.x;side=rightGap>leftGap?"right":"left";edge=side==="right"?right:left}else{for(let xi=0;xi<2;xi++)for(let yi=0;yi<2;yi++)for(let zi=0;zi<2;zi++){anchorV.set(xi?local.max.x:local.min.x,yi?local.max.y:local.min.y,zi?local.max.z:local.min.z).applyMatrix4(object.matrixWorld);const point=projectWorldToScreen(anchorV,camera,rect),preferRight=item.station==="right";if((preferRight&&point.x>edge.x)||(!preferRight&&point.x<edge.x))edge=point}}bridge.anchors.current[layer]={x:edge.x,y:edge.y,r:0,cx:center.x,cy:center.y,name:layer,side}}})}
  const storyMix=smooth(range(p,.035,.16)),anatomyBoost=smooth(range(p,PRE_ANATOMY.start,EXPLOSION.end));scene.background=null;gl.toneMappingExposure=MathUtils.lerp(.96,1.1,storyMix);if(heroSpot.current){heroSpot.current.intensity=MathUtils.lerp(28,3.5,storyMix);heroSpot.current.position.set(mobile?0:.4,4.6,mobile?2.15:2.55);heroSpot.current.target.position.set(rootPose.x,rootPose.y-.03,0);heroSpot.current.target.updateMatrixWorld()}if(ambientLight.current)ambientLight.current.intensity=MathUtils.lerp(.035,.38,storyMix)+anatomyBoost*.06;if(keyLight.current)keyLight.current.intensity=MathUtils.lerp(.05,1.3,storyMix)+anatomyBoost*.12;if(fillLight.current)fillLight.current.intensity=MathUtils.lerp(0,.42,storyMix)+anatomyBoost*.06;if(rimLight.current)rimLight.current.intensity=MathUtils.lerp(0,.16,storyMix);
 });return null;
}
export function ExperienceCanvas({bridge,onPastryReady,onFailure}:{bridge:ExperienceBridge;onPastryReady:()=>void;onFailure:()=>void}){const heroSpot=useRef<SpotLight>(null),ambient=useRef<AmbientLight>(null),key=useRef<DirectionalLight>(null),fill=useRef<DirectionalLight>(null),rim=useRef<DirectionalLight>(null);useEffect(()=>{if(process.env.NODE_ENV==="development")console.debug("[Masa] canvas mounted")},[]);return <div className="canvas-shell" aria-hidden="true"><Canvas dpr={[1,1.35]} shadows={{type:PCFSoftShadowMap}} camera={{position:[0,.1,4.85],fov:34}} gl={{antialias:true,alpha:true,powerPreference:"high-performance"}} onCreated={({gl})=>{gl.outputColorSpace=SRGBColorSpace;gl.toneMapping=ACESFilmicToneMapping;gl.toneMappingExposure=.96}}><ambientLight ref={ambient} intensity={.035} color="#fff6e8"/><spotLight ref={heroSpot} castShadow position={[.4,4.6,2.55]} intensity={28} color="#f2d39a" angle={.42} penumbra={.82} distance={9} decay={2} shadow-bias={-.0003} shadow-normalBias={.02} shadow-mapSize-width={1024} shadow-mapSize-height={1024}/><SpotlightBeam bridge={bridge}/><directionalLight ref={key} position={[3.2,4.2,4]} intensity={.05} color="#fff0d6"/><directionalLight ref={fill} position={[-3,2.2,3]} intensity={0} color="#e3ebef"/><directionalLight ref={rim} position={[-1.5,2.8,-3]} intensity={0} color="#fff4df"/><CanvasBoundary onError={onFailure}><Suspense fallback={null}><SingleBaklava bridge={bridge} onReady={onPastryReady}/></Suspense></CanvasBoundary><Director bridge={bridge} heroSpot={heroSpot} ambientLight={ambient} keyLight={key} fillLight={fill} rimLight={rim}/></Canvas></div>}
