"use client";
import {Canvas,useFrame,useThree} from "@react-three/fiber";
import {Component,ReactNode,Suspense,useEffect,useRef} from "react";
import {Box3,Color,DirectionalLight,MathUtils,Mesh,PerspectiveCamera,PointLight,Vector3} from "three";
import {anatomyInspections,getAnatomyInspectionIndex} from "./content/anatomy";
import {CINEMATIC_CAMERA,getResponsiveProfile} from "./content/responsiveScenes";
import {range,smooth} from "./controllers/math";
import {createRootPose,EXPLOSION,PRE_ANATOMY,RECONSTRUCTION,sampleStoryPose,STORY_SCENES} from "./controllers/sceneTimeline";
import type {ExperienceBridge} from "./experienceTypes";
import {SingleBaklava} from "./models/SingleBaklava";
import {projectWorldToScreen} from "./three/projection";
const target=new Vector3(),selectedWorld=new Vector3(),bounds=new Box3(),anchorV=new Vector3(),leftWorld=new Vector3(),rightWorld=new Vector3();
const edgeCache=new WeakMap<Mesh,{left:Vector3;right:Vector3}>();
function geometryEdges(mesh:Mesh){
 const cached=edgeCache.get(mesh);if(cached)return cached;
 mesh.geometry.boundingBox??mesh.geometry.computeBoundingBox();
 const box=mesh.geometry.boundingBox!,position=mesh.geometry.attributes.position,targetY=MathUtils.lerp(box.min.y,box.max.y,.5),band=Math.max(.001,(box.max.y-box.min.y)*.22),step=Math.max(1,Math.floor(position.count/3200));
 const left=new Vector3(box.min.x,targetY,(box.min.z+box.max.z)*.5),right=new Vector3(box.max.x,targetY,(box.min.z+box.max.z)*.5);let min=Infinity,max=-Infinity;
 for(let vertex=0;vertex<position.count;vertex+=step){anchorV.fromBufferAttribute(position,vertex);if(Math.abs(anchorV.y-targetY)>band)continue;if(anchorV.x<min){min=anchorV.x;left.copy(anchorV)}if(anchorV.x>max){max=anchorV.x;right.copy(anchorV)}}
 const result=leftWorld.copy(left).applyMatrix4(mesh.matrixWorld).x<=rightWorld.copy(right).applyMatrix4(mesh.matrixWorld).x?{left,right}:{left:right,right:left};edgeCache.set(mesh,result);return result;
}
const warmLight=new Color("#f1c078"),neutralLight=new Color("#ead1aa"),anatomyLight=new Color("#e2dacb"),heatLight=new Color("#f1a35d"),mixedLight=new Color();
class CanvasBoundary extends Component<{children:ReactNode;onError:()=>void},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return{failed:true}}componentDidCatch(){this.props.onError()}render(){return this.state.failed?null:this.props.children}}
function Director({bridge,keyLight,fillLight}:{bridge:ExperienceBridge;keyLight:React.RefObject<DirectionalLight|null>;fillLight:React.RefObject<PointLight|null>}){
 const {camera,size,scene,pointer,gl}=useThree(),pose=useRef(createRootPose()),lastMode=useRef("");
 useFrame((state,delta)=>{
  const store=bridge.progress.current;store.current=MathUtils.damp(store.current,store.target,store.reduced?24:16,delta);
  store.velocity=MathUtils.damp(store.velocity,0,8,delta);
  const p=store.current,profile=getResponsiveProfile(size.width,size.height),mode=profile.mode,cinema=CINEMATIC_CAMERA[mode],mobile=mode==="mobile",rootPose=sampleStoryPose(p,size.width,size.height,pose.current),anatomy=smooth(range(p,PRE_ANATOMY.start,EXPLOSION.end)),index=getAnatomyInspectionIndex(p),profileKey=`${profile.kind}:${Math.round(size.width/20)}:${Math.round(size.height/20)}`;
  if(lastMode.current!==profileKey&&camera instanceof PerspectiveCamera){lastMode.current=profileKey;camera.fov=profile.fov;camera.near=.1;camera.far=100;camera.updateProjectionMatrix()}
  const hero=smooth(range(p,.008,STORY_SCENES.hero.revealEnd))*(1-smooth(range(p,.125,STORY_SCENES.hero.end))),history=smooth(range(p,STORY_SCENES.history.start,.17))*(1-smooth(range(p,.265,STORY_SCENES.history.end))),craft=smooth(range(p,STORY_SCENES.craft.start,.31))*(1-smooth(range(p,.42,STORY_SCENES.craft.end))),preparation=smooth(range(p,STORY_SCENES.preparation.start,.465))*(1-smooth(range(p,.5,STORY_SCENES.preparation.end))),quiet=Math.abs(store.velocity)<.00035&&((p<.49)||(p>.965));
  const push=hero*cinema.heroPush*.45+craft*cinema.craftPush*.7-history*.12;
  const idle=store.reduced?0:(quiet?Math.sin(state.clock.elapsedTime*.45)*cinema.idle*.45:0),inertia=store.reduced?0:MathUtils.clamp(store.velocity*4,-.015,.015),pointerWeight=(p<.49||p>.96)?cinema.pointer:0;
  let cameraX=rootPose.x*(mobile?.07:.1)+pointer.x*pointerWeight+inertia,cameraY=.06+rootPose.y*(mobile?.045:.065)+pointer.y*pointerWeight*.55+idle,cameraZ=profile.cameraZ-rootPose.z*(mobile?.07:.1)-push,targetX=rootPose.x*(mobile?.1:.14)+pointer.x*pointerWeight*.35,targetY=rootPose.y*(mobile?.075:.1)+idle*.5;
  if(p>=PRE_ANATOMY.start&&p<RECONSTRUCTION.end){const fit=smooth(range(p,PRE_ANATOMY.start,EXPLOSION.end));cameraX=0;cameraY=mobile?profile.anatomyCenterY*.28:0;cameraZ=profile.anatomyCameraZ+fit*(mobile?.18:.18);targetX=0;targetY=mobile?profile.anatomyCenterY:-.12}
  if(index>=0&&!mobile){const object=bridge.pastry.current[anatomyInspections[index].layers[0]];if(object instanceof Mesh){object.geometry.boundingBox??object.geometry.computeBoundingBox();if(object.geometry.boundingBox){bounds.copy(object.geometry.boundingBox).applyMatrix4(object.matrixWorld).getCenter(selectedWorld);targetY=MathUtils.clamp(selectedWorld.y*.18,-.28,.28);cameraZ-=.18}}}
  camera.position.x=MathUtils.damp(camera.position.x,cameraX,9,delta);camera.position.y=MathUtils.damp(camera.position.y,cameraY,9,delta);camera.position.z=MathUtils.damp(camera.position.z,cameraZ,9,delta);target.set(targetX,targetY,0);camera.lookAt(target);camera.updateMatrixWorld();bridge.camera.current=camera;
  if(index>=0){const item=anatomyInspections[index],canvasRect=gl.domElement.getBoundingClientRect(),rect={left:canvasRect.left,top:canvasRect.top,width:canvasRect.width,height:canvasRect.height};item.layers.forEach(layer=>{const object=bridge.pastry.current[layer];if(object instanceof Mesh&&object.geometry.boundingBox){object.updateWorldMatrix(true,false);const local=object.geometry.boundingBox,centerWorld=local.getCenter(selectedWorld).applyMatrix4(object.matrixWorld),center=projectWorldToScreen(centerWorld,camera,rect);let edge=center,side=item.station;if(mobile){const candidates=geometryEdges(object);leftWorld.copy(candidates.left).applyMatrix4(object.matrixWorld);rightWorld.copy(candidates.right).applyMatrix4(object.matrixWorld);const left=projectWorldToScreen(leftWorld,camera,rect),right=projectWorldToScreen(rightWorld,camera,rect),margin=MathUtils.clamp(size.width*.04,12,18),labelWidth=MathUtils.clamp(size.width*.29,108,118),leftGap=left.x-(margin+labelWidth),rightGap=(size.width-margin-labelWidth)-right.x;side=rightGap>leftGap?"right":"left";edge=side==="right"?right:left}else{for(let xi=0;xi<2;xi++)for(let yi=0;yi<2;yi++)for(let zi=0;zi<2;zi++){anchorV.set(xi?local.max.x:local.min.x,yi?local.max.y:local.min.y,zi?local.max.z:local.min.z).applyMatrix4(object.matrixWorld);const point=projectWorldToScreen(anchorV,camera,rect),preferRight=item.station==="right";if((preferRight&&point.x>edge.x)||(!preferRight&&point.x<edge.x))edge=point}}bridge.anchors.current[layer]={x:edge.x,y:edge.y,r:0,cx:center.x,cy:center.y,name:layer,side}}})}
  const reveal=store.reduced?1:smooth(range(p,0,STORY_SCENES.hero.revealEnd)),regional=MathUtils.clamp(history*.72+craft*.38,0,1);mixedLight.copy(warmLight).lerp(neutralLight,regional).lerp(heatLight,preparation*.22).lerp(anatomyLight,anatomy);scene.background=null;if(keyLight.current){keyLight.current.intensity=.16+1.28*reveal+craft*.16+preparation*.1+anatomy*.14;keyLight.current.color.copy(mixedLight);keyLight.current.position.x=MathUtils.lerp(-2.8,3.5,reveal)-craft*.75;keyLight.current.position.y=4.5-craft*.55}if(fillLight.current)fillLight.current.intensity=.1+.3*reveal+preparation*.06;
 });return null;
}
export function ExperienceCanvas({bridge,onPastryReady,onFailure}:{bridge:ExperienceBridge;onPastryReady:()=>void;onFailure:()=>void}){const key=useRef<DirectionalLight>(null),fill=useRef<PointLight>(null);useEffect(()=>{if(process.env.NODE_ENV==="development")console.debug("[Masa] canvas mounted")},[]);return <div className="canvas-shell" aria-hidden="true"><Canvas dpr={[1,1.35]} camera={{position:[0,.1,4.85],fov:34}} gl={{antialias:true,alpha:true,powerPreference:"high-performance"}}><ambientLight intensity={.52} color="#cbbba6"/><directionalLight ref={key} position={[3.5,4.5,4]} intensity={1.44} color="#f5d7aa"/><directionalLight position={[-3,1,-2]} intensity={.44} color="#858d76"/><pointLight ref={fill} position={[0,-1.5,2]} intensity={.4} color="#985027"/><CanvasBoundary onError={onFailure}><Suspense fallback={null}><SingleBaklava bridge={bridge} onReady={onPastryReady}/></Suspense></CanvasBoundary><Director bridge={bridge} keyLight={key} fillLight={fill}/></Canvas></div>}
